minimum_pre_commit_version: "3.2.0"
files: ^.*\.py$
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.7'
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black